/* CHAR VALUES */
const DEFAULT_VALUE = " ";
const RIFT_VALUE = "R";
const MONSTER_VALUE = "M";
const PORTAL_VALUE = "P";
const CHAR_VALUE = "@";
const UNKNOWN_VALUE = "?";

/* ENVIRONMENT VALUES */
const STARTING_SIZE = 4;
const MONSTER_PROBABILITY_PER_CELL = 0.12;
const RIFT_PROBABILITY_PER_CELL = 0.12;

module.exports = {
  DEFAULT_VALUE,
  RIFT_VALUE,
  MONSTER_VALUE,
  PORTAL_VALUE,
  STARTING_SIZE,
  MONSTER_PROBABILITY_PER_CELL,
  RIFT_PROBABILITY_PER_CELL,
  CHAR_VALUE,
  UNKNOWN_VALUE,
}